

model_list = {
	'TheBloke/toxicqa-Llama2-7B-GGUF':
		{
			'type':'deep_link',
			'name':'TheBloke/toxicqa-Llama2-7B-GGUF',
			'repo_name': 'TheBloke/toxicqa-Llama2-7B-GGUF',
			'file':'toxicqa-llama2-7b.Q5_K_M.gguf'
		},
    'thebloke/speechless-llama2-hermes-orca-platypus-wizardlm-13b.Q5_K_M.gguf':
        {
            'type':'deep_link',
            'name':'thebloke/speechless-llama2-hermes-orca-platypus-wizardlm-13b.Q5_K_M.gguf',
            'repo_name': 'TheBloke/Speechless-Llama2-Hermes-Orca-Platypus-WizardLM-13B-GGUF',
            'file':'speechless-llama2-hermes-orca-platypus-wizardlm-13b.Q5_K_M.gguf'
        },
    'thebloke/llama-2-13b-chat.Q5_K_M.gguf':
        {
            'type':'deep_link',
            'name':'thebloke/llama-2-13b-chat.Q5_K_M.gguf',
            'repo_name': 'TheBloke/Llama-2-13B-chat-GGUF',
            'file':'llama-2-13b-chat.Q5_K_M.gguf'
        },
    'thebloke/solar-10.7b-instruct-v1.0-uncensored.Q5_K_M.gguf':
        {
            'type':'deep_link',
            'name':'thebloke/solar-10.7b-instruct-v1.0-uncensored.Q5_K_M.gguf',
            'repo_name': 'TheBloke/SOLAR-10.7B-Instruct-v1.0-uncensored-GGUF',
            'file':'solar-10.7b-instruct-v1.0-uncensored.Q5_K_M.gguf'
        },
    'thebloke/yarn-mistral-7b-128k.Q5_K_M.gguf':
        {
            'type':'deep_link',
            'name':'thebloke/yarn-mistral-7b-128k.Q5_K_M.gguf',
            'repo_name': 'TheBloke/Yarn-Mistral-7B-128k-GGUF',
            'file':'yarn-mistral-7b-128k.Q5_K_M.gguf'
        },
    'thebloke/neural-chat-7b-v3-1.Q5_K_M.gguf':
        {
            'type':'deep_link',
            'name':'thebloke/neural-chat-7b-v3-1.Q5_K_M.gguf',
            'repo_name': 'TheBloke/neural-chat-7B-v3-1-GGUF',
            'file':'neural-chat-7b-v3-1.Q5_K_M.gguf'
        },
    'thebloke/mistral-7b-instruct-v0.1.Q5_K_M.gguf':
        {
            'type':'deep_link',
            'name':'thebloke/mistral-7b-instruct-v0.1.Q5_K_M.gguf',
            'repo_name': 'TheBloke/neural-chat-7B-v3-1-GGUF',
            'file':'mistral-7b-instruct-v0.1.Q5_K_M.gguf'
        },
    'llmware/dragon-mistral-7b-gguf':
        {
            'type':'llmware',
            'name':'llmware/dragon-mistral-7b-gguf',
        },
    'llmware/dragon-yi-6b-v0':
        {
            'type':'llmware',
            'name':'llmware/dragon-yi-6b-v0',
        },
    'llmware/dragon-red-pajama-7b-v0':
        {
            'type':'llmware',
            'name':'llmware/dragon-red-pajama-7b-v0',
        },
    'llmware/dragon-deci-6b-v0':
        {
            'type':'llmware',
            'name':'llmware/dragon-deci-6b-v0',
        },
    'llmware/dragon-mistral-7b-v0':
        {
            'type':'llmware',
            'name':'llmware/dragon-mistral-7b-v0',
        },
    'llmware/dragon-falcon-7b-v0':
        {
            'type':'llmware',
            'name':'llmware/dragon-falcon-7b-v0',
        },
    'llmware/dragon-llama-7b-v0':
        {
            'type':'llmware',
            'name':'llmware/dragon-llama-7b-v0',
        },
    'llmware/dragon-deci-7b-v0':
        {
            'type':'llmware',
            'name':'llmware/dragon-deci-7b-v0',
        },
    'llmware/bling-sheared-llama-1.3b-0.1':
        {
            'type':'llmware',
            'name':'llmware/bling-sheared-llama-1.3b-0.1',
        },
    'llmware/bling-stable-lm-3b-4e1t-v0':
        {
            'type':'llmware',
            'name':'llmware/bling-stable-lm-3b-4e1t-v0',
        },
    'llmware/bling-sheared-llama-2.7b-0.1':
        {
            'type':'llmware',
            'name':'llmware/bling-sheared-llama-2.7b-0.1',
        },
    'llmware/bling-falcon-1b-0.1':
        {
            'type':'llmware',
            'name':'llmware/bling-falcon-1b-0.1',
        },
    'llmware/bling-red-pajamas-3b-0.1':
        {
            'type':'llmware',
            'name':'llmware/bling-red-pajamas-3b-0.1',
        },
    'llmware/bling-1b-0.1':
        {
            'type':'llmware',
            'name':'llmware/bling-1b-0.1',
        },
    'llmware/bling-cerebras-1.3b-0.1':
        {
            'type':'llmware',
            'name':'llmware/bling-cerebras-1.3b-0.1',
        },
    'llmware/bling-1.4b-0.1':
        {
            'type':'llmware',
            'name':'llmware/bling-1.4b-0.1',
        },
    'llmware/bling-phi-1_5-v0':
        {
            'type':'llmware',
            'name':'llmware/bling-phi-1_5-v0',
        },
    'llmware/bling-phi-2-v0':
        {
            'type':'llmware',
            'name':'llmware/bling-phi-2-v0',
        },
    'llmware/bling-tiny-llama-v0':
        {
            'type':'llmware',
            'name':'llmware/bling-tiny-llama-v0',
        }


}

